<template>
    <div>
        <p>{{ $t('pageNames.waitlist') }}</p>
        <span class="caret"></span>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus condimentum, lorem et sollicitudin cursus, ex nisl euismod dui, vel sagittis purus ipsum quis nunc. Suspendisse placerat mattis molestie. Nam scelerisque est eget elit vulputate tempor. Suspendisse velit nibh, rhoncus vitae accumsan non, ullamcorper vel lectus. Nulla eu ullamcorper tortor, sit amet pharetra ligula. Cras tincidunt auctor nunc. Nullam semper magna tortor, quis sagittis nisi tempor nec. Sed et ornare felis. Fusce nulla velit, vulputate posuere vehicula quis, faucibus a leo. Ut nec lectus efficitur arcu bibendum condimentum. Ut malesuada vehicula finibus. Etiam congue, neque quis commodo egestas, lorem dolor eleifend turpis, eget condimentum magna purus nec lectus. Aliquam sit amet lorem sagittis, finibus nisi ut, consectetur nibh. Fusce posuere nunc elit, fringilla vehicula metus dignissim eu. Cras gravida libero bibendum tellus maximus imperdiet.</p>
        <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis lobortis bibendum magna id tincidunt. Nullam id urna nunc. Praesent imperdiet pharetra vulputate. Nam molestie ligula finibus nulla tincidunt lobortis. Ut aliquet eleifend nibh ac dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec in felis aliquet, posuere augue eget, pretium magna. Nunc ut aliquet leo, nec sollicitudin augue. Quisque sed viverra mauris. Pellentesque viverra velit nec enim pharetra facilisis. Nunc et ex elit. Quisque id malesuada tortor.</p>
        <p>Fusce laoreet semper neque vitae congue. Sed mattis libero at aliquam posuere. Ut ac dolor lobortis, cursus magna finibus, ullamcorper sem. Donec a ex posuere, tempus diam a, varius est. Fusce ullamcorper ornare nisi, id condimentum tortor ultrices vitae. Suspendisse sit amet sapien erat. Duis eleifend, sapien vel tincidunt suscipit, libero enim laoreet nisi, in porta lacus ipsum vitae lectus. Nullam sed est egestas leo pretium posuere.</p>
        <p>Proin bibendum neque sed tristique semper. Nullam at mattis quam. Maecenas malesuada velit erat, eget vehicula erat egestas quis. Vestibulum mattis massa non hendrerit mollis. Aenean scelerisque nibh in elit euismod luctus. Nunc sit amet pretium lacus, non tincidunt magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus hendrerit convallis purus et auctor. Pellentesque quis nunc et nisl eleifend mattis. Mauris ornare nibh faucibus commodo bibendum. Sed vulputate non ligula id imperdiet. Maecenas quis auctor velit. Aenean tempor congue ligula, et aliquet justo interdum vel. Nam sit amet viverra sem, vitae dignissim metus.</p>
        <p>Integer at eros a massa faucibus aliquet. Aliquam eu sem a elit ultrices sagittis vel in lectus. Cras dapibus enim id tincidunt rutrum. Maecenas rhoncus, orci sit amet elementum tempor, dui justo finibus nisl, et elementum mi nisi a ex. Cras nec ligula ipsum. Etiam vitae varius diam, vitae faucibus nunc. Quisque massa urna, varius eu semper vitae, rutrum ut nibh. Praesent hendrerit molestie faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus condimentum, lorem et sollicitudin cursus, ex nisl euismod dui, vel sagittis purus ipsum quis nunc. Suspendisse placerat mattis molestie. Nam scelerisque est eget elit vulputate tempor. Suspendisse velit nibh, rhoncus vitae accumsan non, ullamcorper vel lectus. Nulla eu ullamcorper tortor, sit amet pharetra ligula. Cras tincidunt auctor nunc. Nullam semper magna tortor, quis sagittis nisi tempor nec. Sed et ornare felis. Fusce nulla velit, vulputate posuere vehicula quis, faucibus a leo. Ut nec lectus efficitur arcu bibendum condimentum. Ut malesuada vehicula finibus. Etiam congue, neque quis commodo egestas, lorem dolor eleifend turpis, eget condimentum magna purus nec lectus. Aliquam sit amet lorem sagittis, finibus nisi ut, consectetur nibh. Fusce posuere nunc elit, fringilla vehicula metus dignissim eu. Cras gravida libero bibendum tellus maximus imperdiet.</p>
        <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis lobortis bibendum magna id tincidunt. Nullam id urna nunc. Praesent imperdiet pharetra vulputate. Nam molestie ligula finibus nulla tincidunt lobortis. Ut aliquet eleifend nibh ac dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec in felis aliquet, posuere augue eget, pretium magna. Nunc ut aliquet leo, nec sollicitudin augue. Quisque sed viverra mauris. Pellentesque viverra velit nec enim pharetra facilisis. Nunc et ex elit. Quisque id malesuada tortor.</p>
        <p>Fusce laoreet semper neque vitae congue. Sed mattis libero at aliquam posuere. Ut ac dolor lobortis, cursus magna finibus, ullamcorper sem. Donec a ex posuere, tempus diam a, varius est. Fusce ullamcorper ornare nisi, id condimentum tortor ultrices vitae. Suspendisse sit amet sapien erat. Duis eleifend, sapien vel tincidunt suscipit, libero enim laoreet nisi, in porta lacus ipsum vitae lectus. Nullam sed est egestas leo pretium posuere.</p>
        <p>Proin bibendum neque sed tristique semper. Nullam at mattis quam. Maecenas malesuada velit erat, eget vehicula erat egestas quis. Vestibulum mattis massa non hendrerit mollis. Aenean scelerisque nibh in elit euismod luctus. Nunc sit amet pretium lacus, non tincidunt magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus hendrerit convallis purus et auctor. Pellentesque quis nunc et nisl eleifend mattis. Mauris ornare nibh faucibus commodo bibendum. Sed vulputate non ligula id imperdiet. Maecenas quis auctor velit. Aenean tempor congue ligula, et aliquet justo interdum vel. Nam sit amet viverra sem, vitae dignissim metus.</p>
        <p>Integer at eros a massa faucibus aliquet. Aliquam eu sem a elit ultrices sagittis vel in lectus. Cras dapibus enim id tincidunt rutrum. Maecenas rhoncus, orci sit amet elementum tempor, dui justo finibus nisl, et elementum mi nisi a ex. Cras nec ligula ipsum. Etiam vitae varius diam, vitae faucibus nunc. Quisque massa urna, varius eu semper vitae, rutrum ut nibh. Praesent hendrerit molestie faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
    </div>
</template>

<script>
    export default {
        name: 'waitlist'
    }
</script>